# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='content',
            new_name='quote_text',
        ),
    ]
