# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-31 19:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20180331_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_trips', to='exam.User'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='departure_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='trip',
            name='return_date',
            field=models.CharField(max_length=10),
        ),
    ]
